<div id="search-popup" class="popup-right">
  <div class="search-popup-title">{{__('popup.search_popup.search_title')}}</div>
  <div class="search-popup-desc">{{__('popup.search_popup.whoever_searches')}}</div>
  <div class="search-popup-body form-horizontal">
    <div id="search" class="flex-justify">
      <input type="text" name="search1" value="" placeholder="{{__('popup.search_popup.im_looking_for')}}" class="form-control input-lg" autocomplete="off">

      <ul class="dropdown-menu" style="top: 60px;left: 0"><li class="disabled"><div class="search-suggestion "><div class="center"><div class="title ">Фільтр категорій</div></div></div></li><li data-value="https://wrap.shop/search/?search=123&amp;category_id=110" class="inline active"><a href="#"><div class="search-suggestion category_filter"><div class="center"><div class="name ">Скотч (4)</div></div></div></a></li><li data-value="https://wrap.shop/search/?search=123&amp;category_id=109" class="inline"><a href="#"><div class="search-suggestion category_filter"><div class="center"><div class="name ">Гель для оклейки плівки (2)</div></div></div></a></li><li data-value="https://wrap.shop/search/?search=123&amp;category_id=105" class="inline"><a href="#"><div class="search-suggestion category_filter"><div class="center"><div class="name ">Леза та ножі (2)</div></div></div></a></li><li data-value="https://wrap.shop/search/?search=123&amp;category_id=61" class="inline"><a href="#"><div class="search-suggestion category_filter"><div class="center"><div class="name ">Інструменти / розхідники (1)</div></div></div></a></li><li class="disabled"><div class="search-suggestion "><div class="center"><div class="title ">Товари</div></div></div></li><li data-value="https://wrap.shop/instrumenty-rozhidnyky/skotch/strchka-malyarna-sotro-gold-120-c---limonna-48mm-h-45m" class=""><a href="#"><div class="search-suggestion product"><div class="left"><div class="image "><img src="https://wrap.shop/image/cache/catalog/demo/syncms/c54d6f4a-6267-11ec-0a80-05b700153096_0-70x70.png"></div></div><div class="center"><div class="name ">Стрічка малярна SOTRO GOLD 120 C Лимонна 48 мм, 45 м</div></div><div class="right"><div class="price "><span class="price-base">168.00 ₴</span></div></div></div></a></li><li data-value="https://wrap.shop/instrumenty-rozhidnyky/skotch/strichka-malyarna-sotro-gold-120-c-lymonna-24mm-h-45m" class=""><a href="#"><div class="search-suggestion product"><div class="left"><div class="image "><img src="https://wrap.shop/image/cache/catalog/demo/syncms/9ec5440f-f08d-11ec-0a80-00ac003061e6_0-70x70.png"></div></div><div class="center"><div class="name ">Стрічка малярна SOTRO GOLD 120 C Лимонна 24 мм, 45 м</div></div><div class="right"><div class="price "><span class="price-base">84.00 ₴</span></div></div></div></a></li><li data-value="https://wrap.shop/instrumenty-rozhidnyky/skotch/strchka-malyarna-sotro-gold-120-c---limonna-36mm-h-45m" class=""><a href="#"><div class="search-suggestion product"><div class="left"><div class="image "><img src="https://wrap.shop/image/cache/catalog/demo/syncms/9605235f-6267-11ec-0a80-08380015345d_0-70x70.png"></div></div><div class="center"><div class="name ">Стрічка малярна SOTRO GOLD 120 C Лимонна 36 мм, 45 м</div></div><div class="right"><div class="price "><span class="price-base">92.40 ₴</span></div></div></div></a></li></ul>

      <button type="button" class="button colord btn btn-default btn-lg"><i class="fal fa-search"></i>{{__('popup.search_popup.search')}}
      </button>
    </div>
  </div>
  <div class="close button search-popup-close fal fa-times"></div>
</div>
